version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: library_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: library_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
